Rookout/explorook

- package-lock.json
- package.json
- src/headless.ts
- src/mem-store.ts
- src/rep-store.ts
- src/server.ts
Headless mode will let us easily use Explorook without any GUI in test environments
> Use explorook server without electron

- package-lock.json
- package.json
- src/index.ts
- src/webapp/src/App.css
- src/webapp/src/components/Footer.js
- src/webapp/src/components/RepoListItem.js
- src/webapp/src/components/ReposList.js
part of: https://github.com/Rookout/Rookout/issues/1377
Rook needs electron to start with `--inspect` 
don't know how to do that yet... [waiting for question to be answered](https://github.com/electron-userland/electron-builder/issues/3103)
> Added rook to code and checkbox to enable/disable

- package.json
- src/index.ts
to fix https://github.com/Rookout/Rookout/issues/1739
> patch to fix multiple appimages on autostart

- graphql/schema.graphql
- package.json
- src/api.ts
- src/index.ts
- src/rep-store.ts
1. Added refresh index RPC
1. Notifying of an update manually instead of built-in AutoUpdater because of a known bug
fix https://github.com/Rookout/Rookout/issues/2317
> reindex and windows update notification

- package.json
- src/fsIndexer.ts
Address: https://github.com/Rookout/Rookout/issues/2620
@LiranLast WDYT about `.html` `.scss` `.css` ?
> added some extensions to ignore list

- src/fsIndexer.ts
Address: https://github.com/Rookout/Rookout/issues/2620
@LiranLast WDYT about `.html` `.scss` `.css` ?
> scss and css

- graphql/schema.graphql
- package.json
- src/api.ts
- src/common/repository.ts
- src/git.ts
- src/index-worker.ts
- src/rep-store.ts
- src/server.ts
- tsconfig.json
And did some refactoring  
@MickaelAlliel Let's sit on this together tomorrow morning
> RK-674 Added git info to graphql

- package.json
- src/git.ts
because this is legit error: https://sentry.io/rookout/electron/issues/821475759/?referrer=slack
> RK-738 - supress legit git error

- graphql/schema.graphql
- package.json
- src/api.ts
- src/headless.ts
- src/index-worker.ts
- src/server.ts
- src/webapp/src/components/ReposList.js
I allowed two options:
1. pass no parameters and Explorook will pop the folder picker
2. pass fullpath and Explorook will immediately add the fullpath to its repos list
Not sure we will ever use 2, or if we even want that... @LiranLast @MickaelAlliel  WDYT
> RK-819 Allow adding repo from api request

- .circleci/config.yml
https://circleci.com/gh/Rookout/explorook/238
> RK-975 - homebrew fails to install wine in CI/CD pipeling

- package.json
- src/webapp/src/components/ReposList.js
support multiple folders select
> RK-983 - showing explorook window when open dialog - and rehides

- package-lock.json
- package.json
- src/chrome-opn.d.ts
- src/middlewares.ts
> Revert "RK-1040 - Fix chrome open macos"

- package-lock.json
- package.json
- src/chrome-opn.d.ts
- src/middlewares.ts
> Revert "Revert "RK-1040 - Fix chrome open macos""

- yarn.lock
Recreated `yarn.lock` from old `package-lock.json`  
via: https://yarnpkg.com/lang/en/docs/cli/import/
> created yarn.lock from previous working package-lock.json

- package.json
- src/webapp/yarn.lock
- yarn.lock
upgraded react-scripts, lodash and graphql-yoga
> RK-1686 upgrade some packages with vulnerabilities that do not affect us

- package.json
- src/index.ts
- src/webapp/src/components/Header.js
right click on exit button to open debug tools in production
> RK-2455 - allow debugging through hidden button

- DEVELOPING.MD
- README.md
> just the text

- README.md
> available links

- graphql/schema.graphql
- src/api.ts
- src/index-worker.ts
- src/server.ts
Added more event to track when adding repository
Frontend is already fixed
> RK-3048 - addRepo more analytics

- package.json
- src/index.ts
- src/webapp/package.json
- src/webapp/src/App.js
- src/webapp/src/components/Checkbox.js
- src/webapp/src/components/ConfirmModal.js
- src/webapp/src/components/EulaModal.js
- src/webapp/src/components/Footer.js
- src/webapp/src/components/Header.js
- src/webapp/src/components/RepoListItem.js
- src/webapp/src/components/ReposList.js
- src/webapp/src/components/Token.js
- src/webapp/src/index.js
- src/webapp/src/utils.js
- src/webapp/yarn.lock
@amits1995 All features and components were tested manually and are working the same.
eula flow is now:
first time launch: show eula window, hide window on accept
every launch afterwards, hide window on start
> RK-3374 - Better UX with EULA + Update React to 16.8.0 & Refactor components with hooks

- .circleci/config.yml
- build.sh
- index-worker.html
- package.json
- src/index-worker.ts
- src/index.ts
- src/repoStore.ts
- src/server.ts
- src/webapp/package.json
- webpack.index-worker.config.js
- webpack.main.config.js
- yarn.lock
introduced webpack to bundle dist files
> RK-3464 - use webpack to bundle code

- package.json
- src/webapp/src/components/EulaModal.js
- src/webapp/src/utils.js
https://app.bugsnag.com/rookout/explorook/errors/5d5f33111426890019cb8dc1?filters%5Brelease.seen_in%5D%5B0%5D=1.1.2&filters%5Bapp.release_stage%5D%5B0%5D=production&filters%5Bevent.unhandled%5D%5B0%5D%5Btype%5D=eq&filters%5Bevent.unhandled%5D%5B0%5D%5Bvalue%5D=true
> RK-3599 - Fix exit is undefined when not agreeing to EULA

- package.json
- src/middlewares.ts
- src/server.ts
- yarn.lock
Tested in staging, production, localhost
Replicated the RCE instructions and this fix did not let it happen
> Add CORS to explorook http server and validate URIs we open RK-4098

- package.json
- src/index.ts
- src/server.ts
- src/webapp/src/App.js
> Revert "remove token authorization - rely on CORS only"

- DEVELOPING.MD
- package.json
- src/index.ts
- src/webapp/src/components/Footer.js
- src/webapp/src/components/Header.js
Tested on Windows and Mac.  
On Linux, we have other problems that will be handled separately (not due to this rename)
> rename Explorook -> Rookout Desktop App

- package.json
- src/api.ts
- src/git.ts
- src/webapp/package.json
- src/webapp/yarn.lock
- yarn.lock
solve [this](https://app.bugsnag.com/rookout/explorook/errors/5eccee976ab538001a5fc4ae?filters[event.since][0][type]=eq&filters[event.since][0][value]=7d&filters[error.status][0]=new&filters[app.release_stage][0][type]=eq&filters[app.release_stage][0][value]=production)  
Also added possible fix for [this](https://app.bugsnag.com/rookout/explorook/errors/5ea6581d03dd990018dca8dd?filters[event.since][0][type]=eq&filters[event.since][0][value]=7d&filters[error.status][0]=open&filters[app.release_stage][0][type]=eq&filters[app.release_stage][0][value]=production)
> RK-6124 - upgrade iso-git and refactor

- graphql/schema.graphql
- package.json
- src/exceptionManager.ts
- src/git.ts
Better understand why [this](https://app.bugsnag.com/rookout/explorook/errors/5ecccda46b139a0017ddbf8e?filters[event.since][0][type]=eq&filters[event.since][0][value]=7d&filters[error.status][0]=open&filters[app.release_stage][0][type]=eq&filters[app.release_stage][0][value]=production) happens
> RK-6123 - added breadcrumb to understand an error better

- package.json
- src/git.ts
- src/index.ts
Just removed the token from the context menu.
Didn't delete the rest of the code for now cause you can still have it as a command arg.
Also some linting
> RK-6161 - Removed token from context menu

- src/git.ts
Fixed a bug where we reported that we can't find a git root but we weren't suppose to
> RK-6193 Removed error and united the two get git root functions

- src/webapp/src/components/OnPremConnectionInput.js
- src/webapp/src/components/OnPremConnectionInput.style.js
Redesigning the UI of the test connection button to be more indicative
> Changed the UI for the test connection button RK-6253

- graphql/schema.graphql
- package.json
- src/api.ts
- src/perforceManager.ts
Fetching large Perforce depots takes a lot of time and we get a timeout on the operation.
This new API will get the file tree instead of syncing and will fetch a single file every time we are asking
> RK-6403 - Perforce/get single file

- package.json
- src/api.ts
- src/index-worker.ts
- src/server.ts
- src/webapp/src/components/OnPremConnection.js
Adding an indication when git-on-prem is fetching
> RK-6402 - Git on prem/show loading

- package.json
- src/exceptionManager.ts
- src/index.ts
Get more data from failure of auto updates
> RK-6415 - Track auto updater logs

- package.json
- src/api.ts
- src/git.ts
- src/index-worker.ts
- src/perforceManager.ts
- src/webapp/src/components/ConfirmModal.js
- src/webapp/src/components/GitProtocolPicker.js
- src/webapp/src/components/OnPremConnection.js
- src/webapp/src/components/OnPremConnectionInput.js
- src/webapp/src/components/OnPremConnectionInput.style.js
> RK-6447 - On prem config

- package.json
- src/index-worker.ts
- src/logger.ts
- src/perforceManager.ts
- yarn.lock
Added a log to make the debugging process for Perforce a bit easier
> RK-6485 - Logger/init

- src/api.ts
- src/git.ts
When we have multiple commits for an on prem repo we create a random guid folder for each commit so we can clone both. When we try to delete we try to check the size of the wrong folder (the guid folder instead of the git folder) and get an error
> RK-6500 fixed a problem with deleting a repo with multiple commits

- package.json
- src/git.ts
- src/perforceManager.ts
If the frontend asks for the changelist of a Perforce file we will try to get the label if we can, otherwise return the changelist if possible.
> RK-6634 Added label support for file changelist check

- package.json
- src/webapp/src/components/ConfirmModal.js
On a recent PR I used the "Refactor -> Rename" function of the IDE, which accidentally renamed this label to connectionStringLabel as well. Fixed.
> RK-6687 Fix "Do not show again" label

- package.json
- src/api.ts
- src/git.ts
dont fail clone if clean failed  
full clone instead of shallow
> RK-6825 - small changes to git on prem

- package.json
- src/webapp/yarn.lock
- yarn.lock
Updated dependencies with security issues
> RK-6913 Relocked with newer versions to fix vulnerabilities

- graphql/schema.graphql
- package.json
- src/BitBucketOnPrem.ts
- src/UrlAssembler.d.ts
- src/api.ts
- src/common.ts
- src/middlewares.ts
- src/server.ts
- src/utils.ts
- yarn.lock
Adding queries for bitbucket on prem. Works on my machine
> Bitbucket on prem/init api

- package.json
- src/webapp/yarn.lock
https://rookout.atlassian.net/browse/RK-7095
> Fixed vulnerabilities RK-7095

- package.json
- patches/electron-updater+4.3.5.patch
- yarn.lock
updated our custom security patch - which is needed until [this PR](https://github.com/electron-userland/electron-builder/pull/5082) is in
> RK-7216 - upgrade electron-updater to fix blockmap parse issue

- package.json
- src/index-worker.ts
- src/webapp/src/components/Header.js
Added a button to enable deleting all repos in case there are too many
> RK-7972 - Added a "clear data" button

- .github/codeql/codeql-config.yml
- .github/workflows/code-analysis.yml
Scan results :
https://github.com/Rookout/explorook/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F230%2Fmerge
> RK-8114 - Enable CodeQL on explorook

- package.json
- yarn.lock
no changes in the package except the upgrade for security
> RK-8263 - SNYK-JS-AXIOS-1038255 upgrade analytics-node

- PULL_REQUEST_TEMPLATE.md
- graphql/schema.graphql
- package.json
- src/api.ts
For better future feature handling in the FE
> RK-8542 - Add get-version api

- package.json
- src/api.ts
Making sure the version API works for dev as well
> RK-8550 - Fixed version api for dev

- package.json
- src/webapp/yarn.lock
- yarn.lock
Upgrading lodash to version 14.17.21
> RK-8641 upgrading lodash to 4.17.21

- src/webapp/package.json
No need to bump up explorook version
> RK-8645 - Security vul: Update react scripts

- src/index.ts
Got Error in circleCI:
So This PR fixes it
> RK-8710 - SetInterval Made it more generic

- graphql/schema.graphql
- package.json
- src/api.ts
- src/headless.ts
- src/index-worker.ts
- src/server.ts
- src/webapp/yarn.lock
Added a 'remove repo' API to the desktop app to support removing repos using the rookout's website
> RK-8753 - Added an API to remove repos

- package.json
- src/webapp/yarn.lock
- yarn.lock
snyk vals for may 2021.
didn't upgrade ws yet because it breaks IDE-nav.
will be done in a separate PR.
QA:
made sure explorook is working properly. including IDE-nav
> RK-9527 - Snyk 2021 may partial

- package.json
- src/server.ts
- yarn.lock
updating ws package following May's snyk report.
had some trouble with importing the package after the upgrading but found a solution eventually. https://github.com/websockets/ws/issues/1459#issuecomment-487463423
tested IDE nav with local explorook and production and it worked. but i suggest the reviewer would give it a try as well
> RK-9534 - upgrade ws package

- package.json
- src/BitBucketOnPrem.ts
- src/logger.ts
- src/webapp/src/components/Header.js
Changed default log level to `debug`, made some logs a bit more descriptive.
> RK-9831 - Feat/change log level

- package.json
- src/BitBucketOnPrem.ts
- yarn.lock
> RK-9798 Fix bitbucketonprem inconsistency

- src/webapp/package.json
- src/webapp/yarn.lock
Fixing vulnerabilities according to the Snyk report
> Fixing vuls RK-9721 RK-9725

- src/webapp/package.json
- src/webapp/yarn.lock
> Revert "Fixing vuls RK-9721 RK-9725"

- graphql/schema.graphql
- package.json
- src/BitBucketOnPrem.ts
- src/server.ts
- yarn.lock
> RK-9911 - remove unnecessary url validation

- graphql/schema.graphql
- package.json
- src/server.ts
- yarn.lock
> RK-9938 - remove constraint directive

- .circleci/config.yml
- package.json
install python 3 in circleci publish job, to avoid this:
> RK-10225 - fixing publish ci

- package.json
- src/webapp/package.json
- src/webapp/yarn.lock
- yarn.lock
Updating isomorphic git to version ^1.8.2
> RK-10270 - Updated isomorphic-git

- graphql/schema.graphql
- package.json
- src/api.ts
- src/exceptionManager.ts
goes with https://github.com/Rookout/frontend/pull/3123
get the userEmail from the frontend, save to store, and add it to bugsnag reports
> RK-10249 - Bugsnag user email

- package.json
- src/api.ts
- src/explorook-store.ts
- src/mem-store.ts
handle more cases, with unexpected values.
> RK-10272 - bugfix // userEmail - handle more cases

- package.json
- yarn.lock
Updating electron-notarize to version 1.1.0
> RK-10300 - Upgrading the electron-notorize version

- package.json
- src/webapp/package.json
- src/webapp/yarn.lock
Tested against local rookout deployment.
Validated:
1. bitbucket OP fetching works
2. loading new repos still works
3. deleting previously loaded repos still works
> Fix Snyk Vulnerabilities - August 21

- .circleci/config.yml
> RK-10509 - RK-10509 - fixing bad curl syntax on publish action

- package.json
- src/exceptionManager.ts
- src/index-worker.ts
- src/index.ts
- src/webapp/src/App.js
- src/webapp/src/components/UpdateFailedModal.js
- yarn.lock
Added a new component to display once every 48 hrs when auto upgrade fails.
Added a list of system errors that should not be reported to Bugsnag.
> RK-11304 - Upgrade failed notice

- package.json
- src/webapp/yarn.lock
- yarn.lock
> RK-11646 - Fix Snyk Vuls + bump version

- package.json
- src/BitBucketOnPrem.ts
Optimized source file fetching for BitBucket on prem to fetch larger datasets quicker.
> RK-11675 - Optimize BitBucket OnPrem file tree fetching

- .circleci/config.yml
- package.json
Add arch flag to restore_cache and save_cache to prevent errors when extracting tarball
> RK-11740 - Add arch flag to build to prevent tarball publish errors

- package.json
- src/webapp/yarn.lock
- yarn.lock
Fixed Snyk vulnerabilities. Bump version
> RK-11891 - Fix Snyk Vulnerabilities

- graphql/schema.graphql
- package.json
- src/api.ts
- src/repoStore.ts
Allow refreshing an array of indices with one request (as opposed to only one or all sources in store)
> RK-12215 - Allow refreshing an array of indices with one request 

- graphql/schema.graphql
- package.json
> RK-12230 - Deprecate refreshAllIndices

- .circleci/config.yml
- package.json
Self explanatory, this isn't publishing
> RK-12482 - Change yarn script build name

- graphql/schema.graphql
- package.json
- src/BitBucketOnPrem.ts
- src/api.ts
Bitbucket on prem: add support for checking the page limit of the recursive tree fetching function
> RK-12693 - Bitbucket: add api for checking the page limit of the fetch tree function

- graphql/schema.graphql
- package.json
- src/BitBucketOnPrem.ts
- src/api.ts
Added caching and searching functionality to bitbucket on prem. Fixed get tree limit to include commit in order to avoid problems due to misconfigured main branch
> RK-12751 - Add Bitbucket On Prem Caching and Searching Functionality

- .dockerignore
- Dockerfile
- package.json
- src/headless.ts
Add docker support (not including language servers)
> RK-12796 - Add docker support (not including language servers)

- package.json
- src/server.ts
- yarn.lock
Solve apollo vulnerability: [SNYK-JS-APOLLOSERVERCORE-2928764](https://snyk.io/vuln/SNYK-JS-APOLLOSERVERCORE-2928764)
> RK-12815 - Solve apollo vulnerability: SNYK-JS-APOLLOSERVERCORE-2928764

- Dockerfile
- graphql/schema.graphql
- package.json
Deprecate a query and fix the Dockerfile
> RK-12837 - Deprecate a query and fix the Dockerfile

- package.json
- src/langauge-servers/configStore.ts
- src/langauge-servers/goUtils.ts
- src/langauge-servers/pythonUtils.ts
- yarn.lock
Try to fix find go location. Try to fix python language server for windows.
> RK-12854 - Try to fix language server issues

- package.json
- src/langauge-servers/goUtils.ts
- src/langauge-servers/pythonUtils.ts
- yarn.lock
Go language server, use go env unix systems
> RK-12870 - Go language server, use go env unix systems

- package.json
- yarn.lock
Fix vulnerabilities: 
[SNYK-JS-PARSEPATH-2936439](https://snyk.io/vuln/SNYK-JS-PARSEPATH-2936439)
[SNYK-JS-PARSEURL-2935944](https://snyk.io/vuln/SNYK-JS-PARSEURL-2935944)
[SNYK-JS-PARSEURL-2935947](https://snyk.io/vuln/SNYK-JS-PARSEURL-2935947)
[SNYK-JS-PARSEURL-2936249](https://snyk.io/vuln/SNYK-JS-PARSEURL-2936249)
> RK-12909 - Fix vulnerabilities - upgrade git-url-parse

- package.json
- src/server.ts
Disable introspection and the sandbox landing page to address a security concern
> RK-12781 Disable introspection to address a security concern

- package.json
- upload_release_to_gs.sh
> RK-13046 - Create ARM64 installations

- package.json
- upload_release_to_gs.sh
> RK-13048 - Upload arm64 mac zips

- package.json
- src/index.ts
When doing an auto update, download and update using the arm64 version if this is the user's arch.
> RK-13049 - Auto update to arm64 version, if this is the computer's arch

- graphql/schema.graphql
- package.json
> RK-13205 - Extend BB on prem query

- README.md
- package.json
> RK-13457 - Update README.md

- package.json
- src/index.ts
- src/webapp/src/components/Footer.js
Only auto update on major or minor version change.
Throw error if request for latest explorook version's info is not ok
> RK-13589 Only auto update on major or minor version change

- package.json
- yarn.lock
Update electron to version 19.0.15 for behavior and vulnerability fixes
> RK-13741 - Update electron patch for behavior and vuln fixes

- package.json
- src/exceptionManager.ts
No Bugsnag For Local Development.
Only send to bugsnag if app is prod or running in headless mode
> RK-16794 - No Bugsnag For Local Development

- graphql/schema.graphql
- package.json
- src/BitBucketOnPrem.ts
- src/api.ts
Bitbucket On Prem - Support Fetching Instance Version.
Tested with version 7.13.0 and 5.14.0.
> RK-17730 - Bitbucket On Prem - Support Fetching Instance Version

- package.json
- upload_release_to_gs.sh
> RK-18016 - Remove ch in Get Bucket

- .circleci/config.yml
- package.json
- yarn.lock
Update Electron to 22.3.12.
Update xcode and node in circle ci jobs
> RK-18901 - Update Electron to 22.3.12

- afterSignHook.js
- package.json
Replace Apple Notarize Env Vars
> RK-19881 - Replace Apple Notarize Env Vars

- afterSignHook.js
- package.json
- yarn.lock
* Upgrade Electron Notarize
* Remove appBundleId param which seems to belong to legacy notarize method
> Upgrade Electron Notarize

- package.json
> RK-19887 - Replace CSC_LINK Env Var

- .circleci/config.yml
- package.json
Improved Logic for Replace CSC_LINK Env Var
> RK-19888 - Improved Logic for Replace CSC_LINK Env Var

- .circleci/config.yml
- package.json
Add Logic for Replacing CSC_KEY_PASSWORD Env Var
This is due to us replacing the cert related env vars
> RK-19892 - Add Logic for Replacing CSC_KEY_PASSWORD Env Var

- .circleci/config.yml
- package.json
Fix Publish Cert in CircleCI flow
> RK-19902 - Fix Publish Cert

- DEVELOPING.MD
- package.json
Add Explanation About openssl-legacy-provider
> RK-19904 - Add Explanation About openssl-legacy-provider

- package.json
- src/BitBucketOnPrem.ts
- src/UrlAssembler.d.ts
- src/parseRepo.d.ts
- src/slash.d.ts
- yarn.lock
* Fix BitBucket OnPrem request not being converted to string before being sent.
* Use proper type definitions where possible (parse-repo does not have any, all others were fixed)
Did not test
> RK-19908 - Fix BitBucket Query and Use Proper Type Defs if Possible

- package.json
- src/server.ts
Allowed accessing the app from Dynatrace domains
> RK-20051 - Added Dynatrace domains to CORS

- .circleci/config.yml
Before merging the PR, please bump up the version in `package.json`.
> RK-20408 - Fix publish

- index-worker.html
- package.json
- webpack.index-worker.config.js
Before merging the PR, please bump up the version in `package.json`.
> RK-20418 - Dob fix webpack

- package.json
- yarn.lock
> RK-20506 - Package updates

- .circleci/config.yml
- package.json
> RK-20836 - Update the ev certificate to the 2025 cert
