package.json
src/webapp/package.json
src/webapp/yarn.lock

This PR only upgrade "vulnerable" packages of Explorook's web app  
I had to revert the previous packages upgrade because it broke the usability of the app.  
Currently, there's no reason to upgrade packages of the main app because:
1. They are not fixed in the latest versions
2. They don't really poses any security issue

upgrade webapp "vulnerable" dependencies

---

package.json
src/server.ts

Previous middleware failed the request too soon, even a cors preflight `OPTIONS` request would've failed  
And that led to FE error "Failed to fetch" and FE couldn't know the difference between bad token and no connection
Need this one to go in first https://github.com/Rookout/frontend/pull/580  
Otherwise, we will get a lot of error logs

RK-915 - Auth dont fail cors requests

---

package.json
src/git.ts
src/slash.d.ts

The problem was a bad import of the `slash` package.  
We use the `slash` package to normalize windows path slashes with Unix's path slashes (e.g "\" -> "/").  
The use of slash here got in ~20days ago as part of a fix for Ori Shoshan's friend who had troubles with inner folders in Windows.  
The fact that I used the wrong import syntax, together with the fact that the `slash` package is untyped caused a runtime error that got swallowed by a generic try-catch.  
The original catch was legit because if the folder isn't a git repository an exception is popped by our git third party module (aka `isomorphic-git`).  
Of course, it was just a matter of time this try-catch will catch a legitimate error and ignore it silently.  
Therefore, I:
1. I declared the exact types of the slash module so …

RK-1445 - Fix git repo naming

---

.circleci/config.yml
package.json

@amits1995 Things to think about --> If we fetch from somewhere something from the release page of this repo it will need filtering as there will be 2 releases/tags for each version, 1 from your publishing, 1 from github-enforcer with the formatted release notes.
I can potentially fix that with a check in the enforcer to see if its explorook and do things differently.
#.2 -> Do I need to increment version in package.json for changes in CI?

RK-1649 Generate release notes trigger from circleci

---

src/server.ts

Required for branches as it is the only source possibility

RK-4124 - Add rookout-dev to cors domain whitelist

---

afterSignHook.js
package.json
src/exceptionManager.ts
src/index.ts
src/webapp/package.json
src/webapp/yarn.lock
yarn.lock

[problem](https://app.bugsnag.com/rookout/explorook/errors/5ea05ca7ad751400185a3ad2?filters[event.since][0][type]=eq&filters[event.since][0][value]=7d&filters[error.status][0]=for_review&filters[app.release_stage][0][type]=eq&filters[app.release_stage][0][value]=production): [solution](https://github.com/bugsnag/bugsnag-js/issues/564)

RK-5798 - upgrade bugsnag to solve a TypeError

---

package.json
src/index.ts
src/perforceManager.ts

A customer complained that when he double clicks the tray icon we don't open the config. Fixed.
Also to save PRs I changed it here: Only get workspaces owned by this specific user to make sure we don't get a timeout.

RK-6250 Open explorook on double click

---

package.json
src/git.ts

Cloning and fetching with `--depth=1` to avoid downloading full repo history

RK-6483 - more performant git cloning in current method

---

src/perforceManager.ts

Adding /user/local/bin to the path for mac if it is not there. That is the location in which p4 is if the user installed it properly

Added p4 location to mac path

---

package.json
src/git.ts
src/index.ts

Collect some basic info about git client version and server versions, and whether the servers support the V2 filter capability.  
We want to know how useful would it be to support the filter protocol in order to improve auto fetching robustness.

RK-6742 - track some git versions meta

---

package.json
src/fsIndexer.ts

Ignore more meta files when indexing .NET projects  
[reference](https://app.bugsnag.com/rookout/explorook/errors/5f3be7b0c58ab9001727e113?filters[event.since][0][type]=eq&filters[event.since][0][value]=7d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[app.release_stage][0][type]=eq&filters[app.release_stage][0][value]=production)

RK-7014 - ignore dll and pdb files

---

package.json
src/exceptionManager.ts
src/index-worker.ts
src/index.ts

1. errors are grouped by the file they were thrown from: with `projectRoot` the different filesystems should have similar relative filenames and grouping should be better
1. I changed how we catch errors from autoUpdater - now we get the error object instead of an string with the error.
1. I improved the detection of environment (dev/prod)

RK-7375 - Bugsnag improvements

---

package.json
src/api.ts
src/git.ts
src/index-worker.ts

if the getGitRepo mutation gets duplicates (same git origin, different commit) take the first one and clone only it. (or fetch and checkout if exists).
the previous behavior was to create separated folders and clone each dup.

RK-7625 - GitOnPrem // do not clone dups

---

package.json
src/BitBucketOnPrem.ts

Now using BitBucket Server's pagination to get files longer than 500 lines

Bitbucket op/max file size

---

package.json
src/langauge-servers/javaUtils.ts
yarn.lock

Removed Semver from java utils, that's because java versions are NOT semantic versions.
My mac had version 8.0_202, which isn't semantic so it threw an exception.
Semver is a strict one, I suggest you try it out: https://npm.runkit.com/ ,it will throw exception for '7.0' for example.
So I went for a more natural way, which was taken from RedHat's own Java langserver vscode extension.

Java Extension: Remove semver

---

package.json
src/langauge-servers/configStore.ts
src/langauge-servers/javaUtils.ts

When the explorook is in prod-mode (packaged), its working directory is an unprivileged folder so all downloads should be done in a dedicated folder.
There was an error when trying to check if the file exists, on load so I wrapped it in try/catch for next times.

RK-9018 - Langservers: Save langserver to appdata

---

src/langauge-servers/configStore.ts

Since we use fs.createWriteStream() in order to write the downloaded langserver file, it will not not create the directories on its own.
I ensured that the `langservers` root folder exists, it would accommodate future langServers as well.

RK-9088 - Ensure the langserver exec folder exists

---

package.json
src/langauge-servers/javaUtils.ts
src/langauge-servers/langaugeServer.ts

the encode URI line - which is necessary to encode spaces in mac - is replacing the backslashes that windows URI has, with its urlencode '%5C'.
The URI is gotten from `igit.findRoot()`

RK-9245 - Fix local clone URI in windows

---

package.json
src/BitBucketOnPrem.ts
src/repoStore.ts

1. When querying the file tree, bitbucket OP usually returns array in the values attribute. however, from bugsnag it seems it sometimes doesn't. so when it happens I'm skipping those files and sending to bugsnag the response for further investigation.
https://app.bugsnag.com/rookout/explorook/errors/6053385c1509e100075aa075?filters[event.since][0]=30d&filters[error.status][0]=open
2. we're throwing an unhandled error when fs cannot find a path in the computer. logger.error() would be more fitting.
https://app.bugsnag.com/rookout/explorook/errors/5fa3b18786944c001777aa04?filters[event.since][0]=30d&filters[error.status][0]=open

RK-9398 RK-9397- better error handling in two places

---

package.json
src/server.ts
yarn.lock

reverting the changes of version 1.8.4 (https://github.com/Rookout/explorook/pull/267) but keeping the changes of version 1.8.5 (https://github.com/Rookout/explorook/pull/268) due to a packaging error in the new ws module version

RK-9546 - New working release

---

package.json
src/BitBucketOnPrem.ts

Added optional chaining to user query from BitbucketOnPrem. Trying to prevent [this](https://app.bugsnag.com/rookout/explorook/errors/6114ec940d80850007572584?event_id=6114ec94007f87a5a0420000&i=sk&m=nw) exception that was reported in bugsnag

RK-10119 - Optional chaining for user query

---

package.json
src/webapp/package.json
src/webapp/yarn.lock

Tested against local rookout deployment.
Validated:
- bitbucket OP fetching works
- loading new repos still works
- deleting previously loaded repos still works

Bump node-sass to v6.0.0 to fix a vulnerability

---

.circleci/config.yml

Explorook CircleCI fails because of not-updated cert bundle that doesn't include the new LetsEncrypt root cert.
~~See [this](https://discuss.circleci.com/t/letsencrypt-ssl-root-cert-problems/41379/9) discussion and the [fix](https://blog.bytesguy.com/resolving-lets-encrypt-issues-with-curl-on-macos) I applied.~~
~~This change should be reverted as soon as possible, I will follow-up on this.~~
Better [fix](https://www.identrust.com/support/downloads)

RK-10496 - RK-10496 - Temp Fix CircleCI cert problem on macOS script

---

.circleci/config.yml

Another ricochet from [LetEncrypt cert that went RIP](https://discuss.circleci.com/t/letsencrypt-ssl-root-cert-problems/41379): 
Update to node:14.18.0 in circle ci script image to fix it.
Validated locally it fails with node:8, and works for node:14.18.0

RK-10518 - RK-10518 - Update to node:14.18.0 in circle ci script image

---

.circleci/config.yml

Something is wrong with the CircleCI cache:
I added an env var (currently with the value v1) to the cache key so we can bump (v2, v3 ...) it once we want to reset the cache.

RK-10826 - Try fixing cache error in CircleCI

---

README.md

They were getting 404's, since they lacked the protocol indication.
(I searched for any other similar broken links in MD but found no others.)

RK-11221 - Correct broken links to rookout site, docs

---

package.json
src/deeplinks.ts
src/index.ts

Added deeplinks. Now the app can be opened by typing `rookout://` into your address bar in the browser (on Linux it works only when clicking on an `a` element with this `href`)

RK-11600 - Deeplinks

---

package.json
src/api.ts
tsconfig.json

Try to get appVersion from package json in case remote is empty and if can't fallback to hard coded one.
Bump hard-coded appVersion used in case remote is empty

RK-12004 Update appVersion used if remote is empty

---

graphql/schema.graphql
package.json
src/api.ts
src/repoStore.ts

Support refreshing all repo indices at once, instead of sending a separate refresh request for each one.
Tested with an appropriate FE fix.

RK-12171 - Support refreshing all git indices with a single request

---

.circleci/config.yml
package.json

Updated CI to use new EV certificate.
Not hotswapping the secret with the same one, for clarity and making sure we can revert.

RK-12663 - update ev certificate

---

package.json
src/webapp/src/components/EmptyState.js

Fixing the "Sweet! Rookout desktop app..." message, as it had the word "and" twice.
Before:
After:

RK-12657 Fix message pronunciation - add appears twice

---

package.json
src/headless.ts

* Fix the repo flag in headless mode optional. 
* Add a basic start-headless script. 
* Add short versions of some flags of headless (h is like help, r is like repo).
Tested running in headless mode using the new flag names and without the repo/r flag.

RK-12668 - Improve headless mode flags

---

.circleci/config.yml
package.json

Upgrade the macOS image in circle ci so the node version will be 16.14.2.
Version list is [here](https://circleci.com/docs/2.0/testing-ios/)

RK-12672 - Upgrade the macOS image in circle ci so the node version will be 16.14.2

---

package.json
src/langauge-servers/configStore.ts
src/langauge-servers/goUtils.ts
src/langauge-servers/pythonUtils.ts

Fix the way we find the go installation (use the unix common place for the goroot and add a check for the GOROOT env var). Improve the way we use pip

RK-12928 - Improve go and python language servers for linux, macOS and windows

---

graphql/schema.graphql
package.json
src/common/repository.ts
src/fsIndexer.ts
src/repoStore.ts

Increase the indexer's limit to 300k files (file paths) and add indexRunning to the repo object

RK-13156 - Increase the indexer's limit and and add indexRunning to repo

---

package.json
src/BitBucketOnPrem.ts

Get info from all pages for various bitbucket api functions used by this app.
Fixes edge cases, such as repos that were found but their project / owner was not found (as it was not in the first page of the result)

RK-13166 - Bitbucket On Prem - Use pagination of various api functions

---

PULL_REQUEST_TEMPLATE.md
package.json

If a PR does not update the project's version. The CI/CD fails and bumps the veraion with a direct commit to master.
Therefore, in order to avoid this kind of a mess, I updated the PR instructions of the project to state that the version ALWAYS needs to be bumped up.

RK-13422 - Update the patch instructions of pull requests

---

package.json
yarn.lock

Upgrade electron to the latest patch of major version 19 to fix vulns and bugs
Tests:
Sanity tests for:
Normal Desktop App Usage
Bitbucket On Prem
Java + Python Language servers

RK-13571 - Upgrade electron to 19.0.13

---

afterSignHook.js
package.json

Use the supported tool (notarytool) to notarize the app for macOS.
(Use notarytool instead of the deprecated altool)
Should solve this error:
Warning: altool has been deprecated and, starting in fall 2023, will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software.

RK-13748 - Use the supported tool (notarytool) to notarize the app for macOS

---

package.json
src/index.ts

Add OS info to analytics.
This is due to the upcoming end of support for windows 7+8 in chromium and electron

RK-15775 - Add OS Info to Analytics

---

package.json
src/webapp/package.json
src/webapp/yarn.lock
yarn.lock

Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
Tests done:
None

RK-19292 - Fix semver Vulnerability

---

package.json
src/BitBucketOnPrem.ts

Fixed issue related to lazy fetching of folders that recursively have only one folder as child.
In bitbucket on prem, such folders are fetched at once, as in, in the example below, when Dir1 is lazy loaded, everything until Dir3 will be fetched (as in, dir3 will need to be lazy loaded to get the files, but everything up to it including the dir itself will be added to the tree).
This fix makes sure the relative path of the bottom folder is returned instead of its name, so that the frontend is able to properly fetch it by knowing its path in the repo.
Example of a path that had an issue being lazy loaded:
```
-- Dir1
-- -- Dir2
-- -- -- Dir3
-- -- -- -- File-not-here-because-fetched-when-dir3-lazy-loaded.txt
```

RK-19787 - Bitbucket OnPrem - Fix Lazy Loading Edge Case

---

package.json
yarn.lock

The latests log4js version has a bug with the file appender, according to [this issue](https://github.com/log4js-node/log4js-node/issues/1411), I downgraded it to a working one

RK-20380 - Downgraded log4js version to a working one

---

README.md
package.json
yarn.lock

RK-20397 - [DOB-490] fix old electron

---

.circleci/config.yml
afterSignHook.js
package.json

Before merging the PR, please bump up the version in `package.json`.

RK-20408 - ci-refactoring

---

.circleci/config.yml

According to this [this](https://support.circleci.com/hc/en-us/articles/21521502906267-Why-am-I-seeing-Bad-CPU-type-in-executable-errors-when-running-CircleCI-Builds-on-Apple-Silicon), adding this step should solve the bad CPU type errors we're having since migrating to M1 machines in CircleCI

RK-20853 - CircleCI - Install rosetta to avoid bad CPU error
